name: Python CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Change to your required version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run main.py
        run: python main.py

      - name: Build Success Message
        run: echo "🎉 Build completed successfully! Ready for testing. ✅"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: success()    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Match with the version in the build step

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Tests
        run: python -m unittest discover -s src/tests -p 'test_*.py'
